export const robot =[
    {
        id:0,
        username:'Idriss5234',
        email:'idkr2003@gmail.com'
    },
    {
        id:1,
        username:'Elhabib',
        email:'elhabib@gmail.com'
    },
    {
        id:2,
        username:'mohammed1',
        email:'medx@gmail.com'
    },
    {
        id:3,
        username:'mohammed2',
        email:'lbahja@gmail.com'
    },
    {
        id:4,
        username:'ziyad',
        email:'ziaydox@gmail.com'
    },
    {
        id:5,
        username:'brahim',
        email:'brhoumi@gmail.com'
    },
    {
        id:6,
        username:'simo',
        email:'pinpon@gmail.com'
    },
    {
        id:7,
        username:'younes',
        email:'lcapo@gmail.com'
    },
    {
        id:8,
        username:'aymen',
        email:'ayou@gmail.com'
    },
]

